clw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import accounts
import broadcast
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from clw import settings
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # Examples:
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('broadcast.urls')),
    #url(r'^chat/$', include('chat.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, UserManager
from django.db.models.signals import post_save
from django.utils import timezone
import datetime
from clw import settings


class CustomUser(User):
    middle_name = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    activation_key = models.CharField(max_length=40, blank=True)
    #key_expires = models.DateTimeField(default=timezone.now())
    image = models.ImageField(upload_to='images/', blank=True)
    objects = UserManager()

    def has_voted(self, need):
        if not Votes.objects.filter(need_id=need, user_id=self).first():
            return False
        else:
            return True

    def vote(self, need):
        if not self.has_voted(need):
            v = Votes(user_id=self, need_id=need)
            v.save()



def create_custom_user(sender, instance, created, **kwargs):
    if created:
        values = {}
        for field in sender._meta.local_fields:
            values[field.attname] = getattr(instance, field.attname)
        user = CustomUser(**values)
        user.save()

post_save.connect(create_custom_user, User)


class Thank(models.Model):
    author = models.ForeignKey(CustomUser, related_name='my_thanks', null=True)
    description = models.TextField()
    date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']


class Need(models.Model):
    author = models.ForeignKey(CustomUser, related_name='my_needs', null=True)
    description = models.TextField()
    date = models.DateTimeField(auto_now=True)
    voters = models.ManyToManyField(CustomUser, through='Votes', through_fields=('need_id', 'user_id'))
    active = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-date']


class Votes(models.Model):
    user_id = models.ForeignKey(CustomUser)
    need_id = models.ForeignKey(Need)

chat/models.py
from django.db import models

# Create your models here.

accounts/forms.py
# -*- coding: utf-8
from django import forms
from models import CustomUser
from django.forms import TextInput
from collections import OrderedDict


class EmailForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': u'E-mail'}), required=True)


class LoginForm(EmailForm):
    error_messages = {
            'invalid_data': "Введен неправильный пароль или e-mail",
        }
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': u'Пароль'}), required=True)


class UserForm(forms.Form):
    first_name = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Имя'}))
    last_name = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Фамилия'}))
    middle_name = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Отчество'}))
    city = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Город'}))
    email = forms.EmailField(widget=TextInput(attrs={'placeholder': u'E-mail'}))
    phone = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Телефон'}))


class RegistrationForm(forms.Form):
    first_name = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Имя'}), required=True)
    last_name = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Фамилия'}), required=True)
    middle_name = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Отчество'}), required=True)
    city = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Город'}), required=True)
    email = forms.EmailField(widget=TextInput(attrs={'placeholder': u'E-mail'}), required=True)
    phone = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Телефон'}), required=True)

    class Meta:
        model = CustomUser



    def username(self):
        return self.cleaned_data['email']

    def save(self, commit=True):
        user = CustomUser.objects.create_user(first_name=self.cleaned_data['first_name'],
                                              last_name=self.cleaned_data['last_name'],
                                              middle_name=self.cleaned_data['middle_name'],
                                              city=self.cleaned_data['city'],
                                              email=self.cleaned_data['email'],
                                              phone=self.cleaned_data['phone'],
                                              username=self.username())
        if commit:
            user.is_active = False
            user.save()
        return user


class SetPasswordForm(forms.Form):
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password1 = forms.CharField(label="New password",
                                widget=forms.PasswordInput(attrs={'placeholder': u'Пароль'}),
                                required=True)
    password2 = forms.CharField(label="New password confirmation",
                                widget=forms.PasswordInput(attrs={'placeholder': u'Подтвердите пароль'}),
                                required=True)

    def clean_password(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2


class PasswordChangeForm(forms.Form):

    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
        'password_incorrect': "Your old password was entered incorrectly. "
                                "Please enter it again.",
    }
    old_password = forms.CharField(widget=forms.PasswordInput,
                                   required=False)
    new_password1 = forms.CharField(widget=forms.PasswordInput,
                                    required=False)
    new_password2 = forms.CharField(widget=forms.PasswordInput,
                                    required=False)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

    def clean_new_password(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    first_name = forms.CharField(max_length=20, widget=TextInput(), required=False)
    last_name = forms.CharField(max_length=20, widget=TextInput(), required=False)
    middle_name = forms.CharField(max_length=20, widget=TextInput(), required=False)
    city = forms.CharField(max_length=20, widget=TextInput(), required=False)
    email = forms.EmailField(widget=TextInput(), required=False)
    phone = forms.CharField(max_length=20, widget=TextInput(), required=False)
    file = forms.ImageField(required=False)

    def clean_old_password(self):
        if self.cleaned_data["old_password"]:
            old_password = self.cleaned_data["old_password"]
            if not self.user.check_password(old_password):
                raise forms.ValidationError(
                    self.error_messages['password_incorrect'],
                    code='password_incorrect',
                )
            return old_password

    def save(self, commit=True):
        cd = self.cleaned_data
        user = self.user
        files = self.files
        if cd['first_name']:
            user.first_name = cd['first_name']
        if cd['last_name']:
            user.last_name = cd['last_name']
        if cd['middle_name']:
            user.middle_name = cd['middle_name']
        if cd['city']:
            user.city = cd['city']
        if cd['email']:
            user.email = cd['email']
        if cd['phone']:
            user.phone = cd['phone']
        if files:
            user.image = self.files['file']
        if self.clean_old_password():
            if cd['new_password1'] and cd['new_password2']:
                user.set_password(self.clean_new_password())
        if commit:
            user.save()
        return user


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.ImageField()

broadcast/forms.py
# -*- coding: utf-8
from django import forms
from django.forms import TextInput
from collections import OrderedDict
from models import Task

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=20, widget=TextInput(attrs={'placeholder': u'Название на английском(без пробелов)'}), required=True)
    file = forms.FileField(required=True)
    description = forms.CharField(max_length=400, widget=forms.Textarea(attrs={'placeholder': u'Описание к видео'}))
    verbose_title = forms.CharField(max_length=40, widget=TextInput(attrs={'placeholder': u'Название на кирилице'}), required=True)
    image = forms.ImageField(required=False)
    def save(self, commit=True):
        cd = self.cleaned_data

        task = Task.objects.create(title=cd['title'],
                                   video=cd['file'],
                                   description=cd['description'],
                                   verbose_title=cd['verbose_title'],
                                   image=cd['image'])
        if commit:
            task.save()
        return task



CHOICES = (('ask', 'Вопрос по урокам'),
           ('need', 'Нужда'),
           ('thanks', 'Благодарность'),
           ('witness', 'Свидетельство'))

class FeedBackForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    subject = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES, required=True)

chat/views.py
from django.shortcuts import render

# Create your views here.

templates/forbidd.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block main_content %}

    <section class="forbidd">

        <div class="wrp-1000">

            <div class="wrp-forbidd">

                Страница находится

                <br>

                <br>

                в стадии разработки

                <a href="{% url 'index' %}" class="to-cabinet">Назад в Личный Кабинет</a>

            </div>

        </div>

    </section>

	<section class="s-2">
                <div class="wrp-1000">
                        <div class="header-s-2">Здесь Вы можете оставить свою нужду,<br> благодарность или свидетельство</div>
                        <form action="" method="post" class="need-form">
                        {% csrf_token %}
        <div class="need-wrp">
                                        <ul>
                                                <li>
                                                        <input id="id_subject_0" name="subject" type="radio" value="Вопрос по урокам" />
                            <label for="id_subject_0"> Вопрос по урокам</label>
                                                </li>
                                                <li>
                                                        <input id="id_subject_1" name="subject" type="radio" value="Нужда" />
                            <label for="id_subject_1"> Нужда</label>
                                                </li>
                                                <li>
                                                        <input id="id_subject_2" name="subject" type="radio" value="Благодарность" />
                            <label for="id_subject_2"> Благодарность</label>
                                                </li>
                                                <li>
                                                        <input id="id_subject_3" name="subject" type="radio" value="Свидетельство" />
                            <label for="id_subject_3"> Свидетельство</label>
                                                </li>
                                        </ul>


				</div>
                                <div class="text-area-block">
                                        <textarea id="id_text" name="text" class="need-text" placeholder="Введите Ваш текст сюда..."></textarea>
                    <button type="submit">Отправить</button>
                                </div>
                        </form>
                </div>
        </section>
{% endblock %}


	

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main_content %}
  <div class="banner"></div>

	<section class="s-1">
		<div class="wrp-1000">
			<div class="header-s-1 custom-marg">Приветствую тебя, дорогой Свидетель</div>
			<div class="header-second">КОГДА ТЫ ПРОСМАТРИВАЕШЬ УРОК, ТЕБЕ НУЖНО МОЛИТЬСЯ И РАЗМЫШЛЯТЬ НАД НИМ. И КОГДА ТЫ БУДЕШЬ ПРЕБЫВАТЬ В ЭТОМ МОЛИТВЕННОМ СОСТОЯНИИ, ТО ПРОСЛУШИВАЙ УРОК 2-3 РАЗА
</div>
			<div class="block-video">
				<div class="video-wrp">
{% if video.url  %}
<iframe width="610" height="410"  src="{{video.url}}" frameborder="0" allowfullscreen></iframe>

{% else  %}
<video  controls width="600" height="340" src="{{ video.video.url }}"></video>

{% endif  %}

<a href="{% url 'archive' %}">
					<div class="archive">Перейти в архив видео</div></a>
				</div>
<aside class="video-nav">
					<div class="header-as">Видео уроки</div>
					<div class="body-as">
						{% if tasks %}
                        {% for task in tasks %}
 <a href="http://clw.com.ua{% url 'index' task.title %}">
                            <div class="post-as">
                                                        <p class="title-as">{{ task.verbose_title }}</p>
                                                        <p class="date-as">{{ task.date }}</p>
                                                </div>
                            </a>

                        {% endfor %}
                        {% endif %}
					</div>
				</aside>
			</div>
		</div>
	</section>
	<section class="private">
		<div class="wrp-1000">
<div class="watch-wrap">

                <p class="watch">Смотреть приватный эфир</p>

      <a href="{% url 'private' %}"> <div class="enter-but">Войти</div></a>

            </div>
	</section>
	<section class="test">
		<div class="wrp-1000">
			<div class="header-test">Текстовое задание №{{video.number}}</div>
			<div class="muntyan-wrp">
				<img class="muntyan" src="{{ video.image.url }}" />
				<div class="text-test">
					<div class="header-tt">
						Сегодня я даю тебе задание, которое ты должен выполнять постоянно:
					</div>
                    {% if video.description %}
                    {{ video.description|safe}}
                    {% endif %}
					<!--<ul>
						<li>
							1. С самого утра приветствуй Святого Духа, осознавая, что Он - <span>Творец неба и земли, что Он - твоя опора, Он твой фундамент, Он – твой друг.</span>
						</li>
						<li>
							2. Каждый день произноси слова: <span>«Сделал меня Господь главою, а не хвостом!»</span>. Постарайся осознать, что это есть истина! Примени это конкретно ко всем сферам своей жизни. Исповедуй эти слова в течение всего дня!
						</li>
						<li>
							3. Визуализируй себя как нового человека, как победителя!
						</li>
					</ul>-->
				</div>
			</div>	
		</div>
	</section>
<section class="s-2">
		<div class="wrp-1000">
			<div class="header-s-2">Здесь Вы можете оставить свою нужду,<br> благодарность или свидетельство</div>
<form action="{% url 'feedback' %}" method="post" class="need-form">
                        {% csrf_token %}			
	<div class="need-wrp">
					<ul>
						<li>
							<input id="id_subject_0" name="subject" type="radio" checked  value="ask" />
                            <label for="id_subject_0"> Вопрос по урокам</label>
						</li>
						<li>
							<input id="id_subject_1" name="subject" type="radio" value="need" />
                            <label for="id_subject_1"> Нужда</label>
						</li>
						<li>
							<input id="id_subject_2" name="subject" type="radio" value="thanks" />
                            <label for="id_subject_2"> Благодарность</label>
						</li>
						<li>
							<input id="id_subject_3" name="subject" type="radio" value="witness" />
                            <label for="id_subject_3"> Свидетельство</label>
						</li>
					</ul>
				</div>
				<div class="text-area-block">
					<textarea id="id_text" name="text" class="need-text" placeholder="Выберите ВОПРОС и введите сюда текст..."></textarea>
                    <button type="submit">Отправить</button>
				</div>
			</form>
		</div>
	</section>



<script src="{% static 'js/video2.js' %}"></script>


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block main_content %}
	<section class="s-1 custom-s1">
		<div class="wrp-1000">
			<div class="header-s-1 custom-marg">Вход в систему</div>
			<form action="" method="post" class="main-form">
                {% csrf_token %}
				<div class="inputs">
                    {{ login_form.email }}
                    {{ login_form.password }}
                    

				</div>
                <input type="submit" value="Войти" class="save_button">

			</form>
            <a href="{% url 'forgot_password' %}"> Забыли пароль? </a>
			<div class="error"></div>
		</div>
	</section>

	{% endblock %}

templates/need_board.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main_content %}
	<section class="wood-s">
		<div class="wrp-1000">
			<div class="wood">
				<div class="header-wood">
					<div class="header-hw">Доска молитвенных нужд</div>
					<ul class="nav-hw">
						<li class="ok-li"><a href="{% url 'need_board' 'all' %}">Все нужды</a></li>
						<li class="ok-li"><a href="{% url 'need_board' 'my' %}">Мои нужды</a></li>
						<li>Добавить</li>
					</ul>	
				</div>
				<div class="body-wood">
					<ul class="notes">
                        {% for need in needs %}
						<li class="vidli">
							<p class="from-n">{{need.author.email}}</p>
							<p class="date-n">{{need.date}}</p>
							<div class="text-n scroll-pane">
							<p>{{need.description}}</p>
							</div>
							<table class="ajax-table">
								<tr>
									<td class="left-align">
									<a href="{% url 'vote' need.id  %}"><i class="ajax"></i></a>
										{{need.voters.count}}
									</td>
								</tr>
							</table>
						</li>
                        {% endfor %}

					</ul>
				</div>
				<div class="pagination-2">
					<ul class="pages">
						<li class="page-ar-2 non-back"><<</li>
						<li class="page-numb-2 active-page non-back">1</li>
						<li class="page-numb-2 non-back">2</li>
						<li class="page-numb-2 non-back">3</li>
						<li class="page-ar-2 non-back">>></li>
					</ul>
				</div>
			</div>
		</div>
	</section>
	<section class="s-2">
		<div class="wrp-1000">
			<div class="header-s-2">Здесь Вы можете оставить свою нужду,<br> благодарность или свидетельство</div>
			<form action="{% url 'feedback' %}" method="post" class="need-form">
                        {% csrf_token %}
	<div class="need-wrp">
					<ul>
						<li>
							<input id="id_subject_0" name="subject" type="radio" checked  value="ask" />
                            <label for="id_subject_0"> Вопрос по урокам</label>
						</li>
						<li>
							<input id="id_subject_1" name="subject" type="radio" value="need" />
                            <label for="id_subject_1"> Нужда</label>
						</li>
						<li>
							<input id="id_subject_2" name="subject" type="radio" value="thanks" />
                            <label for="id_subject_2"> Благодарность</label>
						</li>
						<li>
							<input id="id_subject_3" name="subject" type="radio" value="witness" />
                            <label for="id_subject_3"> Свидетельство</label>
						</li>
					</ul>
				</div>
				<div class="text-area-block">
					<textarea id="id_text" name="text" class="need-text" placeholder="Выберите ВОПРОС и введите сюда текст..."></textarea>
                    <button type="submit">Отправить</button>
				</div>
			</form>
		</div>
	</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<!-- the mousewheel plugin - optional to provide mousewheel support -->

<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>



<!-- the jScrollPane script -->

<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>


	<script src="{% static 'js/need.js' %}"></script>

	<script src="{% static 'js/pagination3.js' %}"></script>


{% endblock %}

templates/private.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main_content %}

<div class="banner"></div>
	<section class="s-1">
		<div class="wrp-1000">
			<div class="header-s-1">Приватный эфир 4 измерения</div>
			<div class="block-video">
				<div class="video-wrp">


<video  controls width="600" height = "340" src="{{ video.video.url }}"></video>
<a href="{% url 'archive' %}">					<div class="archive">Перейти в архив видео</div></a>
				</div>
<aside class="video-nav">
					<div class="header-as">Приватный эфир</div>
					<div class="body-as">
						
                        
						<a href="http://clw.com.ua{% url 'private' video.title %}">
                            <div class="post-as">
							<p class="title-as">{{ video.verbose_title }}</p>
							<p class="date-as">{{ video.date }}</p>
						</div>
                            </a>
                       
                       
					</div>
				</aside>
			</div>
			<div class="block-chat">
				<p class="header-ch">Чат приватного эфира</p>
				<div class="body-ch">
					<div class="messages-ch">
						<div class="post-ch">
							<div class="info-ch">
								<span class="who-ch">Разработчик,</span>
								<span class="when-ch">18 Мая 2015 13:36:02</span>
							</div>
							<div class="mess-ch">Чат в стадии разработки</div>
						</div>
					</div>
				</div>
				<div class="chat-form">
					<textarea name="message" class="chat" placeholder="Нажмите кнопку 'Отправить' или Enter, чтобы отправить сообщение"></textarea>
					<div class="chat-form-but">Отправить</div>
				</div>
			</div>
		</div>
	</section>
<section class="s-2">
		<div class="wrp-1000">
			<div class="header-s-2">Здесь Вы можете оставить свою нужду,<br> благодарность или свидетельство</div>
			<form action="{% url 'feedback' %}" method="post" class="need-form">
                {% csrf_token %}
				<div class="need-wrp">
					<ul>
						<li>
							<input id="id_subject_0" name="subject" type="radio" checked  value="ask" />
                            <label for="id_subject_0"> Вопрос по урокам</label>
						</li>
						<li>
							<input id="id_subject_1" name="subject" type="radio" value="need" />
                            <label for="id_subject_1"> Нужда</label>
						</li>
						<li>
							<input id="id_subject_2" name="subject" type="radio" value="thanks" />
                            <label for="id_subject_2"> Благодарность</label>
						</li>
						<li>
							<input id="id_subject_3" name="subject" type="radio" value="witness" />
                            <label for="id_subject_3"> Свидетельство</label>
						</li>
					</ul>
				</div>
				<div class="text-area-block">
					<textarea id="id_text" name="text" class="need-text" placeholder="Выберите ВОПРОС и введите сюда текст..."></textarea>
                    <button type="submit">Отправить</button>
				</div>
			</form>
		</div>
	</section>
<script src="{% static 'js/chat.js' %}"></script>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main_content %}
<div class="banner2"></div>
<section class="s-1 custom-s1">
		<div class="wrp-1000">
			<div class="header-second custom-head">Вы первый раз посетили этот сайт и хотите получать видео и текстовые задания ? Для этого необходимо СОЗДАТЬ ЛИЧНЫЙ КАБИНЕТ</div>
			<form action="" method="post" class="main-form">
                {% csrf_token %}
				<div class="inputs">
					{{register_form.last_name}}
                    {{register_form.first_name}}
                    {{register_form.middle_name}}
                    <div class="block"></div>
                    {{register_form.city}}
                    {{register_form.phone}}
<input id="id_email" class="jmail"  name="email" placeholder="E-mail" type="text" />
				</div>

				<button id="submit-main" type="submit">Создать</button>
                  <!-- {% csrf_token %}
{% for field in register_form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field }}
    </div>
{% endfor %}
<button class="save-but" type="submit">Создать</button>-->

			</form>
<div class="error">*Введите, пожалуйста, свои данные</div>
		</div>
	</section>
<!-- POP-UP -->
<div class="log-pop-up">
  <div class="wrap-this">
   <div class="log-window">
       <div class="close"></div>
    <p class="header-lw">Вход в личный кабинет</p>
    <form action="{% url 'login_2'  %}" method="post" class="login-form">
 {% csrf_token %}
                        {{login_form.email}}
                        {{login_form.password}}
     <button type="submit">
      Войти в личный кабинет
      <span class="box-shadow"></span>
     </button>
    </form>
<br>
<p><a href="{% url 'forgot_password'  %}" style="text-decoration: underline;"> Забыли пароль? </a><p> 
   </div>
   <div class="forgot-pass">
    Если Вас забыли свой пароль или какие то другие проблемы со входом, напишите на эл. почту <span>ponyaid@gmail.com</span>
   </div>
  </div>
 </div>




  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="{% static 'js/header_menu.js' %}"></script>
        <script src="{% static 'js/login.js' %}"></script>
        <script src="{% static 'js/forms.js' %}"></script>
<script src="{% static  'js/videos.js' %}"></script>
        <script src="{% static  'js/videos.js' %}"></script>
{% endblock %}

templates/thank_board.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main_content %}
	<section class="paper-sec">
		<div class="paper-wrap">
			<div class="picture-ribbons">
				Благодарности
				<div class="ribbon-text left-ribbon">
					<a href="{% url 'index' %}">Назад в личный кабинет</a>
				</div>
				<div class="ribbon-text right-ribbon">Добавить</div>
			</div>
			<ul class="all-thanxs">

                {% for thank in thanks  %}
				<a href="#">
					<li>
						<p class="text-thx">
							{{thank.description}}
						</p>
						<p class="from-thx">
							<span>{{thank.author.email}}, </span>
							{{thank.date}}
						</p>
					</li>
				</a>
                {% endfor %}


			</ul>
			<div class="pagination-2">
					<ul class="pages">
						<li class="page-ar-2"><<</li>
						<li class="page-numb-2 active-page">1</li>
						<li class="page-numb-2">2</li>
						<li class="page-numb-2">3</li>
						<li class="page-ar-2">>></li>
					</ul>
				</div>
		</div>
	</section>
	<section class="s-2">
		<div class="wrp-1000">
			<div class="header-s-2">Здесь Вы можете оставить свою нужду,<br> благодарность или свидетельство</div>
			<form action="{% url 'feedback' %}" method="post" class="need-form">
                        {% csrf_token %}
	<div class="need-wrp">
					<ul>
						<li>
							<input id="id_subject_0" name="subject" type="radio" checked  value="ask" />
                            <label for="id_subject_0"> Вопрос по урокам</label>
						</li>
						<li>
							<input id="id_subject_1" name="subject" type="radio" value="need" />
                            <label for="id_subject_1"> Нужда</label>
						</li>
						<li>
							<input id="id_subject_2" name="subject" type="radio" value="thanks" />
                            <label for="id_subject_2"> Благодарность</label>
						</li>
						<li>
							<input id="id_subject_3" name="subject" type="radio" value="witness" />
                            <label for="id_subject_3"> Свидетельство</label>
						</li>
					</ul>
				</div>
				<div class="text-area-block">
					<textarea id="id_text" name="text" class="need-text" placeholder="Выберите ВОПРОС и введите сюда текст..."></textarea>
                    <button type="submit">Отправить</button>
				</div>
			</form>
		</div>
	</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'js/to_need.js' %}"></script>
<script src="{% static 'js/pagination.js' %}"></script>
{% endblock %}

templates/uploader.html
{% extends 'base.html' %}
{% block main_content %}

	<section class="s-1 custom-s1">
		<div class="wrp-1000">
			<div class="header-s-1 custom-marg">Загрузить видео</div>
			<form enctype="multipart/form-data" method="post" class="user-form">
                <div class="pick-file">
                {% csrf_token %}
                <div class="inputs">
                    {{ form.title }}
                    {{ form.verbose_title }}
                </div>
                <input id="id_file" name="file" type="file" />
					<label for="id_file">
                     <span>Обзор</span>
					</label>

                    <textarea cols="40" id="id_description" maxlength="400" name="description" rows="10" class="need-text" placeholder="Введите описание видео сюда..."></textarea>


                <input type="submit" value="Сохранить" class="save_button">
                    </div>
            </form>
			<div class="error"></div>
		</div>
	</section>
{% endblock %}